# Generated by Django 3.2.5 on 2021-07-26 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseForArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_rus', models.CharField(max_length=50, unique=True, verbose_name='Название на рус')),
                ('slug_article', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('long_description', models.TextField(verbose_name='Длинное описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка месяца')),
                ('pub_date', models.DateField(verbose_name='Дата начала')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=50, unique=True, verbose_name='Название курса')),
                ('slug_course', models.SlugField(max_length=200, unique=True, verbose_name='URL')),
                ('name_subject', models.CharField(max_length=50, verbose_name='Пердмет')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('long_description', models.TextField(verbose_name='Длинное описание')),
                ('image_course', models.ImageField(upload_to='', verbose_name='Картинка курса')),
                ('pub_date', models.DateField(verbose_name='Дата начала')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип',
                'verbose_name_plural': 'Типы',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер домашнего задания')),
                ('pdf_file_for_student', models.FileField(blank=True, null=True, upload_to='', verbose_name='Домашнее задание без решения')),
                ('pdf_file_for_teacher', models.FileField(blank=True, null=True, upload_to='', verbose_name='Домашнее задание с решением')),
                ('pub_date_for_student', models.DateTimeField(verbose_name='Дата публикации без решения')),
                ('deadline', models.DateTimeField(verbose_name='Дедлайн')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_month_set', to='courses.baseforarticle', verbose_name='Месяц')),
            ],
            options={
                'verbose_name': 'Домашнее задание',
                'verbose_name_plural': 'Домашние задания',
            },
        ),
        migrations.AddField(
            model_name='baseforarticle',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bind_course_set', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='baseforarticle',
            name='type_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_model_set', to='courses.type', verbose_name='Тип'),
        ),
    ]
